In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

Data Collection and Data Processing

In [4]:
landslide_data = pd.read_csv('../data_set/landslide_dataset.csv', header=0)

In [5]:
landslide_data.head()

,Rainfall_mm,Slope_Angle,Soil_Saturation,Vegetation_Cover,Earthquake_Activity,Proximity_to_Water,Landslide,Soil_Type_Gravel,Soil_Type_Sand,Soil_Type_Silt
0,206.181018,58.275001,0.892798,0.339463,4.390047,0.099975,1,0,0,0
1,218.887334,36.679801,0.657147,0.360355,4.141029,0.832443,1,0,0,1
2,181.850867,31.363874,0.673362,0.221697,5.311891,0.023062,1,0,0,1
3,228.716199,38.995134,0.618666,0.489502,4.581928,0.785176,1,0,0,1
4,179.951067,42.998205,0.836966,0.118580,5.518862,0.450499,1,0,0,0

In [6]:
landslide_data.shape

(2000, 10)

In [7]:
landslide_data.describe()

,Rainfall_mm,Slope_Angle,Soil_Saturation,Vegetation_Cover,Earthquake_Activity,Proximity_to_Water,Landslide,Soil_Type_Gravel,Soil_Type_Sand,Soil_Type_Silt
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.00000,2000.0000,2000.00000
mean,176.688462,29.985404,0.540316,0.522862,3.604771,1.001867,0.500000,0.25850,0.2415,0.26100
std,65.724685,15.175902,0.295665,0.260426,1.895955,0.579964,0.500125,0.43792,0.4281,0.43929
min,50.036151,5.003944,0.000652,0.100005,0.001641,0.000653,0.000000,0.00000,0.0000,0.00000
25%,128.379762,18.018061,0.265634,0.295475,1.973415,0.500808,0.000000,0.00000,0.0000,0.00000
50%,177.013772,27.772833,0.599887,0.500191,3.996429,0.999761,0.500000,0.00000,0.0000,0.00000
75%,228.742286,41.683190,0.801994,0.740690,5.233897,1.505294,1.000000,1.00000,0.0000,1.00000
max,299.919102,59.966732,0.998831,0.999837,6.498670,1.999636,1.000000,1.00000,1.0000,1.00000

In [8]:
landslide_data['Landslide'].value_counts()

Landslide
1    1000
0    1000
Name: count, dtype: int64

1 -> Landslide  
0 -> No landslide

In [9]:
landslide_data.groupby('Landslide').mean()

,Rainfall_mm,Slope_Angle,Soil_Saturation,Vegetation_Cover,Earthquake_Activity,Proximity_to_Water,Soil_Type_Gravel,Soil_Type_Sand,Soil_Type_Silt
Landslide,,,,,,,,,
0,127.111331,17.717390,0.282473,0.748140,1.974215,1.502907,0.517,0.483,0.000
1,226.265592,42.253418,0.798160,0.297583,5.235326,0.500827,0.000,0.000,0.522

In [10]:
# seprating data and Labels
X = landslide_data.drop(columns='Landslide', axis=1)
Y = landslide_data['Landslide']

In [12]:
print(X)
print(Y)

      Rainfall_mm  Slope_Angle  Soil_Saturation  Vegetation_Cover  \
0      206.181018    58.275001         0.892798          0.339463
1      218.887334    36.679801         0.657147          0.360355
2      181.850867    31.363874         0.673362          0.221697
3      228.716199    38.995134         0.618666          0.489502
4      179.951067    42.998205         0.836966          0.118580
...           ...          ...              ...               ...
1995   195.650778    27.084662         0.567332          0.556801
1996   197.339684    22.715510         0.037470          0.517580
1997    75.759674     6.631750         0.266207          0.925309
1998    50.919297    16.603380         0.014794          0.954346
1999   188.083126    28.372795         0.093188          0.516938

      Earthquake_Activity  Proximity_to_Water  Soil_Type_Gravel  \
0                4.390047            0.099975                 0
1                4.141029            0.832443                 0
2                5.311891            0.023062                 0
3                4.581928            0.785176                 0
4                5.518862            0.450499                 0
...                   ...                 ...               ...
1995             3.472594            1.323190                 1
1996             0.673632            1.921158                 1
1997             0.306690            1.944876                 0
1998             2.073630            1.111595                 1
1999             3.959366            1.043214                 1

      Soil_Type_Sand  Soil_Type_Silt
0                  0               0
1                  0               1
2                  0               1
3                  0               1
4                  0               0
...              ...             ...
1995               0               0
1996               0               0
1997               1               0
1998               0               0
1999               0               0

[2000 rows x 9 columns]
0       1
1       1
2       1
3       1
4       1
       ..
1995    0
1996    0
1997    0
1998    0
1999    0
Name: Landslide, Length: 2000, dtype: int64

Training and Test data  

X_train = training data  
X_test = testing data  
Y_train = label of training data  
Y_test = label of testing data

In [13]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, stratify=Y, random_state=1)

In [14]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
print(X.shape, X_train.shape, X_test.shape)

(2000, 9) (1600, 9) (400, 9)

In [15]:
print(X_train)
print(Y_train)

[[-0.51710176 -1.3642508  -1.77415552 ... -0.58697344  1.76140969
  -0.58601101]
 [-1.6119082  -0.83245142 -1.60065215 ...  1.70365461 -0.56772709
  -0.58601101]
 [-1.63431118 -1.46260926 -1.66996769 ...  1.70365461 -0.56772709
  -0.58601101]
 ...
 [ 0.80699997  0.74562295  0.34801862 ... -0.58697344 -0.56772709
  -0.58601101]
 [ 0.18863081  0.4876449   1.11209083 ... -0.58697344 -0.56772709
   1.70645259]
 [ 0.00980803  0.47934923  0.7971671  ... -0.58697344 -0.56772709
  -0.58601101]]
1957    0
1800    0
1956    0
752     1
1525    0
       ..
1499    0
1211    0
852     1
544     1
903     1
Name: Landslide, Length: 1600, dtype: int64

Model Training --> Logistic Regression

In [16]:
model = LogisticRegression(max_iter=1000)

In [17]:
model.fit(X_train, Y_train)

LogisticRegression(max_iter=1000)

Model Evaluation

In [18]:
#accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [19]:
print("Accuracy on training data: ", training_data_accuracy)

Accuracy on training data:  1.0

In [20]:
# accuracy on testing data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [21]:
print("Accuracy on test data : ", test_data_accuracy)

Accuracy on test data :  1.0

In [22]:
input_data = (206.1810178271,58.2750007243,0.8927975767,0.3394633937,4.3900466011,0.0999749158,0,0,0)

# changing the input_data to a numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the np array as we are predicting for one instance
input_data_reshape = input_data_as_numpy_array.reshape(1, -1)

prediction = model.predict(input_data_reshape)
print(prediction)


# just a print logic
if(prediction[0] == 0):
  print("No")
else:
  print("Ohh yes")

[1]
Ohh yes